version: '3'

services:
  web:
    image: jgbrioso/cars_php
    container_name: cars_php
    links:
      - "db:finals_default"
    depends_on:
      - db
    volumes:
      - ./var/www/html/
    ports:
       - "8000:80"
    stdin_open: true
    tty: true

  db:
    image: jgbrioso/cars_db
    container_name: cars_db
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: job
      MYSQL_PASSWORD:
      MYSQL_DATABASE: cars





