version: '3'

services:
  web:
    image: cars_php
    container_name: cars_php
    links:
      - "db:finalproj_default"
    depends_on:
      - db
    volumes:
      - ./var/www/html/
    ports:
       - "8000:80"
    stdin_open: true
    tty: true

  db:
    image: cars_db
    container_name: cars_db
    ports:
      - "3306:3306"

